### ISSUE TITLE
Unable to build project: plug-in not found: Manifold

### ISSUE THREAD

**Issue by sshcrack** [PacifistMC/Forgix#52]
Hi, I'm unable to build the project. I've used the template generator and don't really know if it is a issue with this project or the template one.
Another question: Are all versions built when running the global `build` task?

```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':neoforge:compileTestJava'.
> Compilation failed; see the compiler output below.
  error: plug-in not found: Manifold
  1 error

* Try:
> Check your code and dependencies to fix the compilation error(s)
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':forge:compileTestJava'.
> Compilation failed; see the compiler output below.
  error: plug-in not found: Manifold
  1 error

* Try:
> Check your code and dependencies to fix the compilation error(s)
> Run with --scan to get full insights.
==============================================================================
```

This is the project I'm using:
[project.zip](https://github.com/user-attachments/files/20761894/talking-colonists.zip)

**Comment by Ran-Mewo** [comment]
all projects are built when running the global build or assemble task, versions have to be built separately but you can easily make a script for building all versions 
this seems to be an issue with the template, I'll take a look

for now use the `assemble` task instead of `build`
